filter:
    paths:
        - 'class-mundschenk-wp-requirements.php'
        - 'tests/*'

build:
    cache:
        directories:
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
            # vendor is already included.

    environment:
        rabbitmq: false
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        php:
            version: 7.1
    tests:
        override:
            - phpcs-run -p class-mundschenk-wp-requirements.php tests/ --ignore=tests/coverage --extensions=php

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_code_sniffer: false
    php_cs_fixer: false
    external_code_coverage: true
